# Generated by Django 4.2.1 on 2023-05-11 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_imgfile_post_mainphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mainphoto',
            new_name='imgfile',
        ),
    ]
