# Generated by Django 4.2.1 on 2023-05-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_examplemodel_remove_post_imgfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.AddField(
            model_name='post',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
